#!/bin/bash

# Test Real-time Branding Updates
# This script demonstrates the real-time branding functionality

echo "=== Real-time Branding Test ==="
echo ""
echo "Prerequisites:"
echo "1. Backend server must be running (npm run start:dev)"
echo "2. Frontend must be running (npm run dev)"
echo "3. You must be logged in as Super Admin"
echo ""
echo "Test Steps:"
echo "1. Open two browser windows/tabs with the Platform Branding Settings page"
echo "2. In one window, change the primary color"
echo "3. Click 'Save Settings'"
echo "4. Observe that the other window automatically updates with the new color"
echo ""
echo "Expected Behavior:"
echo "- Both windows should show the 'Live' indicator (green with Wifi icon)"
echo "- When you save in one window, the other window should:"
echo "  * Show a toast notification: 'Branding updated by another user'"
echo "  * Update the preview panel with the new colors"
echo "  * Update the form fields with the new values"
echo ""
echo "WebSocket Events:"
echo "- 'branding:updated' - Specific branding update event"
echo "- 'settings:updated' - Generic settings update event with type='branding'"
echo ""
echo "To monitor WebSocket events in browser console:"
echo "1. Open DevTools (F12)"
echo "2. Go to Console tab"
echo "3. Look for messages like:"
echo "   - 'Received real-time branding update:'"
echo "   - 'Settings updated:'"
echo ""
echo "Backend Logs:"
echo "Look for these log messages in the backend console:"
echo "- 'Broadcasting branding update to all clients'"
echo "- WebSocket connection/disconnection messages"
echo ""
echo "=== Manual Test Checklist ==="
echo "[ ] Two browser windows open with Platform Branding Settings"
echo "[ ] Both windows show 'Live' indicator"
echo "[ ] Change primary color in Window 1"
echo "[ ] Save settings in Window 1"
echo "[ ] Window 2 receives toast notification"
echo "[ ] Window 2 preview updates automatically"
echo "[ ] Window 2 form fields update automatically"
echo "[ ] Check browser console for WebSocket events"
echo "[ ] Check backend logs for broadcast message"
echo ""
echo "=== API Endpoint Test ==="
echo ""
echo "You can also test the API directly:"
echo ""
echo "# Get current branding"
echo "curl -X GET http://localhost:3000/super-admin/settings/branding \\"
echo "  -H 'Authorization: Bearer YOUR_TOKEN'"
echo ""
echo "# Update branding (this will trigger WebSocket broadcast)"
echo "curl -X PUT http://localhost:3000/super-admin/settings/branding \\"
echo "  -H 'Authorization: Bearer YOUR_TOKEN' \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{"
echo "    \"colors\": {"
echo "      \"primary\": \"#FF0000\","
echo "      \"secondary\": \"#00FF00\","
echo "      \"accent\": \"#0000FF\","
echo "      \"background\": \"#FFFFFF\","
echo "      \"text\": \"#000000\""
echo "    },"
echo "    \"fonts\": {"
echo "      \"heading\": \"Roboto\","
echo "      \"body\": \"Roboto\""
echo "    },"
echo "    \"companyName\": \"Test Company\""
echo "  }'"
echo ""
echo "=== Troubleshooting ==="
echo ""
echo "If real-time updates don't work:"
echo "1. Check WebSocket connection status (should show 'Live' indicator)"
echo "2. Check browser console for connection errors"
echo "3. Verify backend is running and accessible"
echo "4. Check that JWT token is valid"
echo "5. Verify CORS settings allow WebSocket connections"
echo ""
echo "Common Issues:"
echo "- 'Offline' indicator: WebSocket connection failed"
echo "  * Check backend is running"
echo "  * Check CORS_ORIGIN environment variable"
echo "  * Check JWT_SECRET is configured"
echo ""
echo "- No toast notification on update:"
echo "  * Check browser console for WebSocket events"
echo "  * Verify both windows are connected to same backend"
echo "  * Check backend logs for broadcast message"
echo ""
